### ISSUE TITLE
NMI interrupt source

### ISSUE THREAD

**Issue by eriksl** [StefanBruens/ESP8266_new_pwm#2]
http://www.esp8266.com/viewtopic.php?p=52345#p52345

Please use NMI interrupt source, the "normal" source doesn't always work (for me: never).

**Comment by StefanBruens** [comment]
I have added the option to trigger a level 3, i.e. NMI, interrupt instead of the normal level 1 interrupt.

If this is really useful can be debated, as it will still use the the first free-running timer (FRC1), so you can not use it for anything else. E.g. I have no idea what happens if you attach both the NMI and the standard interrupt to FRC1.

As an alternative, you can use the FRC2, but only via the os_delay_..., os_timer_... functions.
